version: '3'
services:
  web:
    image: nginx
    restart: always
    container_name: poo-php 
    ports :
     - "80:80"
    volumes:
     - .:/var/www/html/
     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - php
     - db

  php:
    build: docker/php
    restart: always
    volumes:
      - .:/var/www/html
      
  db:
    image: mariadb:10.3
    container_name: poo-db
    ports :
      - "3306:3306"
    volumes:
      - ./docker/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
        - MYSQL_ROOT_PASSWORD=S3CR3T
        - MYSQL_DATABASE=design
        - MYSQL_USER=design-pat
        - MYSQL_PASSWORD=S3CR3T
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: poo-admin
    ports:
      - "8080:80"
    environment:
        - PMA_ARBITRARY=1
        - MYSQL_ROOT_PASSWORD=S3CR3T
        - MYSQL_DATABASE=design
        - MYSQL_USER=design-pat
        - MYSQL_PASSWORD=S3CR3T
    depends_on:
      - db

      